[package]
name = "cli"
edition = "2024"
version.workspace = true

[dependencies]
anyhow.workspace = true
bip39 = { workspace = true, features = ["rand"] }
bitcoin.workspace = true
breez-sdk-spark.workspace = true
clap = { workspace = true, features = ["derive"] }
dirs.workspace = true
rustyline = { workspace = true, features = ["derive"] }
serde.workspace = true
serde_json.workspace = true
shlex.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
tracing.workspace = true

[lints]
workspace = true
