[package]
name = "rust_lib_breez_sdk_spark"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
async-trait.workspace = true
breez-sdk-common.workspace = true
breez-sdk-macros.workspace = true
breez-sdk-spark.workspace = true
extend.workspace = true
flutter_rust_bridge.workspace = true

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }
