name: Build Language bindings
on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'commit/tag/branch reference'
        required: true
        type: string
      kotlin:
        required: false
        type: boolean
        default: false
      swift:
        required: false
        type: boolean
        default: false
      python:
        required: false
        type: boolean
        default: false
      csharp:
        required: false
        type: boolean
        default: false
      golang:
        required: false
        type: boolean
        default: false
  workflow_call:
    inputs:
      repository:
        description: 'sdk repository, defaults to current repository'
        required: false
        type: string
      ref:
        description: 'commit/tag/branch reference'
        required: true
        type: string
      kotlin:
        required: false
        type: boolean
        default: false
      swift:
        required: false
        type: boolean
        default: false
      python:
        required: false
        type: boolean
        default: false
      csharp:
        required: false
        type: boolean
        default: false
      golang:
        required: false
        type: boolean
        default: false
    secrets:
      REPO_SSH_KEY:
        required: true

jobs:
  build-language-bindings:
    runs-on: ubuntu-latest
    if: ${{ inputs.swift || inputs.python }}
    steps:
      - name: Checkout breez-sdk-spark repo
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository || github.repository }}
          ref: ${{ inputs.ref || github.sha }}
  
      - name: Setup build environment
        uses: ./.github/actions/setup-build
        with:
          ssh-private-key: ${{ secrets.REPO_SSH_KEY }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build C# binding
        if: ${{ inputs.csharp }}
        run: make bindings-csharp

      - name: Archive C# binding
        if: ${{ inputs.csharp }}
        uses: actions/upload-artifact@v4
        with:
          name: bindings-csharp
          path: lib/bindings/ffi/csharp/*

      - name: Build Kotlin binding
        if: ${{ inputs.kotlin }}
        run: make bindings-kotlin

      - name: Archive Kotlin binding
        if: ${{ inputs.kotlin }}
        uses: actions/upload-artifact@v4
        with:
          name: bindings-kotlin
          path: lib/bindings/ffi/kotlin/*

      - name: Build Kotlin multiplatform binding
        if: ${{ inputs.kotlin }}
        run: make bindings-kotlin-multiplatform

      - name: Archive Kotlin multiplatform binding
        if: ${{ inputs.kotlin }}
        uses: actions/upload-artifact@v4
        with:
          name: bindings-kotlin-multiplatform
          path: lib/bindings/ffi/kotlin-multiplatform/*

      - name: Build Python binding
        if: ${{ inputs.python }}
        run: make bindings-python

      - name: Archive Python binding
        if: ${{ inputs.python }}
        uses: actions/upload-artifact@v4
        with:
          name: bindings-python
          path: lib/bindings/ffi/python/breez_sdk_spark.py

      - name: Build Swift binding
        if: ${{ inputs.swift }}
        run: make bindings-swift

      - name: Archive Swift binding
        if: ${{ inputs.swift }}
        uses: actions/upload-artifact@v4
        with:
          name: bindings-swift
          path: lib/bindings/ffi/swift/*

