name: Build bindings for Windows
on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'commit/tag/branch reference'
        required: true
        type: string
  workflow_call:
    inputs:
      repository:
        description: 'sdk repository, defaults to current repository'
        required: false
        type: string
      ref:
        description: 'commit/tag/branch reference'
        required: true
        type: string
      use-dummy-binaries:
        description: 'If true, creates dummy binaries rather than real binaries'
        required: false
        type: boolean
        default: false
      uniffi-25:
        description: 'If true, builds additional bindings for Uniffi 0.25'
        required: false
        type: boolean
        default: false
    secrets:
      REPO_SSH_KEY:
        required: true

jobs:
  build:
    if: ${{ !inputs.use-dummy-binaries }}
    runs-on: windows-latest
    name: build ${{ matrix.target }}
    strategy:
      matrix:
        target: [
          i686-pc-windows-msvc,
          x86_64-pc-windows-msvc,
        ]
    steps:
    - name: checkout
      uses: actions/checkout@v4
      with: 
        ref: ${{ inputs.ref }}
        repository: ${{ inputs.repository || github.repository }}

    - name: Setup build environment
      uses: ./.github/actions/setup-build
      with:
        ssh-private-key: ${{ secrets.REPO_SSH_KEY }}
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install ${{ matrix.target }}
      run: |
        rustup target add ${{ matrix.target }}

    - name: Build bindings
      working-directory: lib/bindings
      run: cargo build --release --target ${{ matrix.target }}

    - name: Archive release
      uses: actions/upload-artifact@v4
      with:
        name: bindings-${{ matrix.target }}
        path: target/${{ matrix.target }}/release/breez_sdk_spark_bindings.dll

  build-dummies:
    if: ${{ inputs.use-dummy-binaries }}
    runs-on: ubuntu-latest
    name: build dummies ${{ matrix.target }}
    strategy:
      matrix:
        target: [
          i686-pc-windows-msvc,
          x86_64-pc-windows-msvc,
        ]
    steps:
      - name: Build dummy windows ${{ matrix.target }}
        run: |
          touch breez_sdk_spark_bindings.dll

      - name: Upload dummy windows ${{ matrix.target }} artifact
        uses: actions/upload-artifact@v4
        with:
          name: bindings-${{ matrix.target }}
          path: ./*